export const GET_ALL_WORKERS = 'get_all_workers'
export const GET_ALL_WORKERS_FAILED = 'GET_ALL_WORKERS_FAILED'
export const GET_ALL_WORKERS_SUCCESS = 'GET_ALL_WORKERS_SUCCESS'

export const GET_ALL_PROJECTS = 'get_all_projects'
export const GET_ALL_PROJECTS_FAILED = 'GET_ALL_PROJECTS_FAILED'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'

export const GET_WORKER_COMMENTS = 'GET_WORKER_COMMENTS'
export const GET_WORKER_COMMENTS_FAILED = 'GET_WORKER_COMMENTS_FAILED'
export const GET_WORKER_COMMENTS_SUCCESS = 'GET_WORKER_COMMENTS_SUCCESS'

export const GET_WORKER_SKILLS = 'GET_WORKER_SKILLS'
export const GET_WORKER_SKILLS_FAILED = 'GET_WORKER_SKILLS_FAILED'
export const GET_WORKER_SKILLS_SUCCESS = 'GET_WORKER_SKILLS_SUCCESS'

export const ON_BID_PROJECT = 'ON_BID_PROJECT'
export const ON_BID_PROJECT_FAILED = 'ON_BID_PROJECT_FAILED'
export const ON_BID_PROJECT_SUCCESS = 'ON_BID_PROJECT_SUCCESS'

export const ON_ADD_COMMENT2 = 'ON_ADD_COMMENT2'
export const ON_ADD_COMMENT2_FAILED = 'ON_ADD_COMMENT2_FAILED'
export const ON_ADD_COMMENT2_SUCCESS = 'ON_ADD_COMMENT2_SUCCESS'


