export const GET_PROFILE = 'get_profile'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'

export const GET_BALANCE = 'GET_BALANCE'
export const GET_BALANCE_FAILED = 'GET_BALANCE_FAILED'
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'

export const CHANGE_PASS = 'CHANGE_PASS'
export const CHANGE_PASS_FAILED = 'CHANGE_PASS_FAILED'
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS'

export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'

export const GET_TRANSACTION = 'GET_TRANSACTION'
export const GET_TRANSACTION_FAILED = 'GET_TRANSACTION_FAILED'
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS'

export const ON_ADD_COMMENT = 'ON_ADD_COMMENT'
export const ON_ADD_COMMENT_FAILED = 'ON_ADD_COMMENT_FAILED'
export const ON_ADD_COMMENT_SUCCESS = 'ON_ADD_COMMENT_SUCCESS'

export const ON_ADD_SKILL = 'ON_ADD_SKILL'
export const ON_ADD_SKILL_FAILED = 'ON_ADD_SKILL_FAILED'
export const ON_ADD_SKILL_SUCCESS = 'ON_ADD_SKILL_SUCCESS'

export const ON_DELETE_SKILL = 'ON_DELETE_SKILL'
export const ON_DELETE_SKILL_FAILED = 'ON_DELETE_SKILL_FAILED'
export const ON_DELETE_SKILL_SUCCESS = 'ON_DELETE_SKILL_SUCCESS'

export const GET_USER_SKILLS = 'GET_USER_SKILLS'
export const GET_USER_SKILLS_FAILED = 'GET_USER_SKILLS_FAILED'
export const GET_USER_SKILLS_SUCCESS = 'GET_USER_SKILLS_SUCCESS'