export const GET_PROFILE = 'get_profile'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'

export const CHANGE_PASS = 'CHANGE_PASS'
export const CHANGE_PASS_FAILED = 'CHANGE_PASS_FAILED'
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS'