export const GET_ALL_PROJECTS = 'get_all_projects'
export const GET_ALL_PROJECTS_FAILED = 'GET_ALL_PROJECTS_FAILED'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'

export const GET_USER_PROJECTS = 'get_user_projects'
export const GET_USER_PROJECTS_FAILED = 'GET_USER_PROJECTS_FAILED'
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS'