export const GET_ALL_PROJECTS = 'get_all_projects'
export const GET_ALL_PROJECTS_FAILED = 'GET_ALL_PROJECTS_FAILED'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'

export const GET_USER_PROJECTS = 'get_user_projects'
export const GET_USER_PROJECTS_FAILED = 'GET_USER_PROJECTS_FAILED'
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS'

export const ADD_PROJECT = 'add_project'
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'

export const GET_PROGRESS_PROJECTS = 'GET_PROGRESS_PROJECTS'
export const GET_PROGRESS_PROJECTS_FAILED = 'GET_PROGRESS_PROJECTS_FAILED'
export const GET_PROGRESS_PROJECTS_SUCCESS = 'GET_PROGRESS_PROJECTS_SUCCESS'

export const GET_MILESTONES = 'GET_MILESTONES'
export const GET_MILESTONES_FAILED = 'GET_MILESTONES_FAILED'
export const GET_MILESTONES_SUCCESS = 'GET_MILESTONES_SUCCESS'

export const GET_CONTRACT = 'GET_CONTRACT'
export const GET_CONTRACT_FAILED = 'GET_CONTRACT_FAILED'
export const GET_CONTRACT_SUCCESS = 'GET_CONTRACT_SUCCESS'

export const ON_ADD_TASK = 'ON_ADD_TASK'
export const ON_ADD_TASK_FAILED = 'ON_ADD_TASK_FAILED'
export const ON_ADD_TASK_SUCCESS = 'ON_ADD_TASK_SUCCESS'

export const ON_DELETE_TASK = 'ON_DELETE_TASK'
export const ON_DELETE_TASK_FAILED = 'ON_DELETE_TASK_FAILED'
export const ON_DELETE_TASK_SUCCESS = 'ON_DELETE_TASK_SUCCESS'

export const ON_BID_PROJECT = 'ON_BID_PROJECT'
export const ON_BID_PROJECT_FAILED = 'ON_BID_PROJECT_FAILED'
export const ON_BID_PROJECT_SUCCESS = 'ON_BID_PROJECT_SUCCESS'

export const ON_DELETE_BID = 'ON_DELETE_BID'
export const ON_DELETE_BID_FAILED = 'ON_DELETE_BID_FAILED'
export const ON_DELETE_BID_SUCCESS = 'ON_DELETE_BID_SUCCESS'

export const GET_BID_LIST_HIRE = 'GET_BID_LIST_HIRE'
export const GET_BID_LIST_HIRE_FAILED = 'GET_BID_LIST_HIRE_FAILED'
export const GET_BID_LIST_HIRE_SUCCESS = 'GET_BID_LIST_HIRE_SUCCESS'

export const GET_BID_LIST_LANCER = 'GET_BID_LIST_LANCER'
export const GET_BID_LIST_LANCER_FAILED = 'GET_BID_LIST_LANCER_FAILED'
export const GET_BID_LIST_LANCER_SUCCESS = 'GET_BID_LIST_LANCER_SUCCESS'

export const ON_DELETE_PROJECT = 'ON_DELETE_PROJECT'
export const ON_DELETE_PROJECT_FAILED = 'ON_DELETE_PROJECT_FAILED'
export const ON_DELETE_PROJECT_SUCCESS = 'ON_DELETE_PROJECT_SUCCESS'

export const ON_CHOOSE_BID = 'ON_CHOOSE_BID'
export const ON_CHOOSE_BID_FAILED = 'ON_CHOOSE_BID_FAILED'
export const ON_CHOOSE_BID_SUCCESS = 'ON_CHOOSE_BID_SUCCESS'

export const ON_CANCEL_CONTRACT = 'ON_CANCEL_CONTRACT'
export const ON_CANCEL_CONTRACT_FAILED = 'ON_CANCEL_CONTRACT_FAILED'
export const ON_CANCEL_CONTRACT_SUCCESS = 'ON_CANCEL_CONTRACT_SUCCESS'

export const ON_CONFIRM_CONTRACT = 'ON_CONFIRM_CONTRACT'
export const ON_CONFIRM_CONTRACT_FAILED = 'ON_CONFIRM_CONTRACT_FAILED'
export const ON_CONFIRM_CONTRACT_SUCCESS = 'ON_CONFIRM_CONTRACT_SUCCESS'

export const ON_APPLY_TASK = 'ON_APPLY_TASK'
export const ON_APPLY_TASK_FAILED = 'ON_APPLY_TASK_FAILED'
export const ON_APPLY_TASK_SUCCESS = 'ON_APPLY_TASK_SUCCESS'

export const ON_APPLY_FINISH = 'ON_APPLY_FINISH'
export const ON_APPLY_FINISH_FAILED = 'ON_APPLY_FINISH_FAILED'
export const ON_APPLY_FINISH_SUCCESS = 'ON_APPLY_FINISH_SUCCESS'

export const ON_COMFIRM_TASK = 'ON_COMFIRM_TASK'
export const ON_COMFIRM_TASK_FAILED = 'ON_COMFIRM_TASK_FAILED'
export const ON_COMFIRM_TASK_SUCCESS = 'ON_COMFIRM_TASK_SUCCESS'

export const ON_COMFIRM_FINISH = 'ON_COMFIRM_FINISH'
export const ON_COMFIRM_FINISH_FAILED = 'ON_COMFIRM_FINISH_FAILED'
export const ON_COMFIRM_FINISH_SUCCESS = 'ON_COMFIRM_FINISH_SUCCESS'

export const ON_CHECK_PAYMENT = 'ON_CHECK_PAYMENT'
export const ON_CHECK_PAYMENT_FAILED = 'ON_CHECK_PAYMENT_FAILED'
export const ON_CHECK_PAYMENT_SUCCESS = 'ON_CHECK_PAYMENT_SUCCESS'

export const ON_SUBMIT_PAYMENT = 'ON_SUBMIT_PAYMENT'
export const ON_SUBMIT_PAYMENT_FAILED = 'ON_SUBMIT_PAYMENT_FAILED'
export const ON_SUBMIT_PAYMENT_SUCCESS = 'ON_SUBMIT_PAYMENT_SUCCESS'









// "ID": "a527acd2-bda9-4347-9879-d4ac9c84e403",
// "ProjectID": "c5cfda5f-d484-4c4f-a290-55eafdfbf877",
// "LancerID": "c65e3ce3-29a7-4533-a006-e506995abaf9",
// "Winner": null,
// "Cap": 5000000,
// "Description": "Манайх medee.mn, online-solution.mn, task.mn зэрэг вэбүүдийг хийж байсан туршлагатай. Танай вэбийг чанарын өндөр түвшинд хийж гүйцэтгэнэ.",
// "Time": "70"